export default {
  USER_ERROR: "USER_ERROR",
  SET_USER_DATA_SUCCESS: "SET_USER_DATA_SUCCESS",
  SET_USER_DATA_START: "SET_USER_DATA_START",
  SET_USER_DATA_RESET: "SET_USER_DATA_RESET",
  SET_USER_DATA_FAILURE: "SET_USER_DATA_FAILURE",
  SET_USER_AUTHENTICATED: "SET_USER_AUTHENTICATED",
};
